#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/loans
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#      use-new-id-generator-mappings: false
#      naming:
#        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy